[build]
publish = "public"
command = "npm run build:preview"

[context.production]
command = "npm run build:production"

[[redirects]]
  from = "/how-to/*"
  to = "/user-guides/how-to/"
  status = 301