[build]
publish = "public"
command = "npm run build:preview"

[context.production]
command = "npm run build:production"

[[redirects]]
  from = "/docs/how-to/*"
  to = "/docs/user-guides/how-to/*"
  status = 301